version: '3'
services:
  filegator:
    build: .
    image: filegator/filegator:latest
    restart: always
    ports:
      - "8099:8080"
    volumes:
      - $FILEGATOR_PATH:/var/www/filegator/repository
      - $FILEGATOR_PVT_PATH:/var/www/filegator/private