services:
  atomic-server:
    # You can create a .env using `atomic-server generate-dotenv`
    # env_file: ".env"
    image: joepmeneer/atomic-server
    container_name: atomic-server
    ports:
      - 70:80
    volumes:
      - $ATOMIC_PATH:/atomic-storage