services:
  memcached:
    image: memcached
    container_name: yopass-memcached
    restart: always
    expose:
      - "11211"

  yopass:
    image: jhaals/yopass
    container_name: yopass
    restart: always
    ports:
      - "8090:1337"
    command: "--memcached=memcached:11211 --port 1337"
    depends_on:
      - memcached
