services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOMARR_DATA:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=$HOMARR_SECRET_KEY
    ports:
      - '7575:7575'