services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - $HOMARR_CONFIGS:/app/data/configs
      - $HOMARR_ICONS:/app/public/icons
      - $HOMARR_DATA:/data
      - $HOMARR_LOGO:/app/public/imgs/logo
      - $HOMARR_FAVICON:/app/public/imgs/favicon
      - $HOMARR_BACKGROUND:/app/public/backgrounds
    environment:
      - SECRET_ENCRYPTION_KEY=$HOMARR_SECRET_KEY
    ports:
      - '7575:7575'