services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:1.44.0
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOMARR_DATA:/appdata
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - SECRET_ENCRYPTION_KEY=$HOMARR_SECRET_KEY
    ports:
      - '7575:7575'