services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox-desktop
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC # Change to your timezone, e.g., Europe/London
    volumes:
      - ./config:/config
      - $DOWNLOADS_PATH:/downloads
    ports:
      - 3101:3001
    shm_size: "1gb"
    restart: unless-stopped